### ISSUE TITLE
nginx: [emerg] "keepalive_timeout" directive invalid value in /etc/nginx/nginx.conf

### ISSUE THREAD

**Issue by s2074135** [mriedmann/humhub-docker#149] opened 2020-10-27 16:15 UTC
Hi 

Today I tried to upgrade my humhub-docker image from version 1.6.2 to version 1.6.3. Unfortunately, the new container keeps crashing with the following error message:

>  _nginx: [emerg] "keepalive_timeout" directive invalid value in /etc/nginx/nginx.conf:29_

Returning to the old version (1.6.2) resolves the problem. 

When looking at the /etc/nginx/nginx.conf config file at line 29 I see the following statement:

`    keepalive_timeout  ${NGINX_KEEPALIVE_TIMEOUT};`

In my case, the variable $NGINX_KEEPALIVE_TIMEOUT should be replaced by a default value of 65, as I have not defined said variable in my docker-compose.yml file.

I tried to emulate the problem by executing the following statements manually in the running 1.6.3 container:

```
export NGINX_KEEPALIVE_TIMEOUT=65
defined_envs=$(printf "\${%s} " $(env | grep -E "^NGINX_.*" | cut -d= -f1))
envsubst "$defined_envs" </etc/nginx/nginx.conf >/tmp/nginx.conf
```

The variable does not get set correctly in /tmp/nginx.conf. I also tried to set it explicitly in docker-compose.yml, with the same result. The problem pertains as well to other variables in /etc/nginx.nginx.conf such as NGINX_CLIENT_MAX_BODY_SIZE.

I am a bit at a loss on what to do here. I will consider host mounting nginx.conf and run with a static configuration if everything else fails.

Anyone seen this error before or know what I could investigate next?

Thank you.

Thomas

**Comment by mriedmann** [comment] 2020-10-27 16:43
We will try to investigate that as soon as possible. Sorry for the inconvenience.

Short question: Is https://github.com/mriedmann/humhub-docker/issues/148 a duplicate of this?

**Comment by s2074135** [comment] 2020-10-27 20:06
> We will try to investigate that as soon as possible. Sorry for the inconvenience.
> 
> Short question: Is #148 a duplicate of this?

Yes, sorry. I closed #148

**Comment by s2074135** [comment] 2020-10-27 20:41
Correction to my initial post:

> The variable does not get set correctly in /tmp/nginx.conf. I also tried to set it explicitly in docker-compose.yml, with the same result. 

envsubst **does** pick up the variable if it is defined in docker-compose.yml and envsubst ist executed manually from within the container. But when I let entrypoint (docker-compose up) to do the work, it is still not set in /etc/nginix/nginix.conf

**Comment by mriedmann** [comment] 2020-10-27 21:41
ok very interesting. I know this error but I thought I have fixed it. Can you please provide the output from the entrypoint-script? Currently I am not able to reconstruct the problem. Maybe you can also provide your affected docker-compose file? Would be a big help to find the problem. Thx.

**Comment by s2074135** [comment] 2020-10-28 08:06
@mriedmann thank you for your offer to help. Version 1.6.3:

/ # cat /etc/nginx/nginx.conf 
```
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
error_log  /dev/stderr  notice;
#error_log  logs/error.log  info;

pid        /run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  /dev/stdout  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  ${NGINX_KEEPALIVE_TIMEOUT};

    #gzip  on;
    charset utf-8;
    client_max_body_size ${NGINX_CLIENT_MAX_BODY_SIZE};

    server {
        listen 80;
        listen [::]:80;

        server_name _ default;

        root /var/www/localhost/htdocs;

        index index.php index.html;

        location ~ ^/(status|ping)$ {
            log_subrequest off;
            access_log off;
            allow 127.0.0.1;
            deny all;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass ${NGINX_UPSTREAM};
        }

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~* \.(?:ico|gif|jpe?g|png|ttf|woff)$ {
            access_log off;
            expires 30d;
            add_header Pragma public;
            add_header Cache-Control "public, mustrevalidate, proxy-revalidate";
        }

        location ~ ^/(protected|framework|themes/\w+/views|\.|uploads/file) {
            deny all;
        }

        location ~ ^/(assets|static|themes|uploads) {
            expires 10d;
            add_header Cache-Control "public, no-transform";
        }

        location ~ \.php$ {
            try_files $uri =404;

            fastcgi_index index.php;
            fastcgi_split_path_info ^(.+\.php)(.*)$;

            #let yii catch the calls to unexisting PHP files
            set $fsn /index.php;
            if (-f $document_root$fastcgi_script_name){
                    set $fsn $fastcgi_script_name;
            }

            fastcgi_keep_conn on;
            include fastcgi_params;
            fastcgi_param PATH_INFO       $fastcgi_path_info;
            fastcgi_param SCRIPT_FILENAME $document_root$fsn;
            fastcgi_pass ${NGINX_UPSTREAM};
        }

        location ~ /\.ht {
            deny all;
        }

        location /protected {
            deny all;
        }

        location /uploads/file {
            deny all;
        }
    }
}
```

**Comment by s2074135** [comment] 2020-10-28 08:18
And here the corresponding docker-compose.yml:

```
version: '3.1'
services:
  humhub:
    restart: always
    image: mriedmann/humhub:1.6.3
    container_name: humhub
    hostname: humhub
    environment:
      # 1 => true, set to "false" to disable.
      HUMHUB_DB_USER: ${HUMHUB_DB_USER}
      HUMHUB_DB_PASSWORD: ${HUMHUB_DB_PASSWORD}
      HUMHUB_DB_HOST: 'db'
      HUMHUB_DB_NAME: 'humhub'
      HUMHUB_AUTO_INSTALL: 1
      HUMHUB_DEBUG: 1
      HUMHUB_PROTO: 'http'
      HUMHUB_HOST: humhum.com # alt.humhub.com 
      # Reverseproxy variables
      VIRTUAL_HOST: humhum.com # alt.humhumb.com
      # Let's encrpyt variables
      LETSENCRYPT_HOST: humhum.com # alt.humhub.com 
      LETSENCRYPT_EMAIL: admin@humhum.com
      NGINX_KEEPALIVE_TIMEOUT: '65'
      NGINX_CLIENT_MAX_BODY_SIZE: '10m'

    volumes:
      - '/opt/docker/humhub/data/humhub/protected/config:/var/www/localhost/htdocs/protected/config'
      - '/opt/docker/humhub/data/humhub/protected/modules:/var/www/localhost/htdocs/protected/modules'
      - '/opt/docker/humhub/data/humhub/uploads:/var/www/localhost/htdocs/uploads'
      - '/opt/docker/humhub/data/humhub/themes:/var/www/localhost/htdocs/themes/humhum'
      # Not strictly necessary, just to shut up the log file
      - '/opt/docker/humhub/data/humhub/protected/runtime/logs:/var/www/localhost/htdocs/protected/runtime/logs/'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - coltero

  db:
    restart: always
    image: mariadb:latest
    container_name: mariadb
    hostname: humhub
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: 'humhub'
      MYSQL_USER: ${HUMHUB_DB_USER}
      MYSQL_PASSWORD: ${HUMHUB_DB_PASSWORD}
    volumes:
      - '/opt/docker/humhub/data/mariadb/:/var/lib/mysql'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - coltero

networks:
  coltero:
    external: true

```

**Comment by s2074135** [comment] 2020-10-28 08:27
And here the (hopefully) relevant entries from the log file:

```
# docker-compose up 
Creating humhub  ... done
Creating mariadb ... done
Attaching to mariadb, humhub
humhub | /docker-entrypoint.sh: Starting pre-launch ...
humhub | /docker-entrypoint.sh: Existing installation found!
humhub | /docker-entrypoint.sh: Waiting for database connection...
mariadb | 2020-10-28 08:18:51+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.6+maria~focal started.
mariadb | 2020-10-28 08:18:51+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mariadb | 2020-10-28 08:18:51+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.6+maria~focal started.
.
.
.
humhub | db (192.168.0.7:3306) open
.
.
humhub | /docker-entrypoint.sh: Updating from version v1.6.2 to v1.6.3
humhub | Yii Migration Tool (based on Yii v2.0.36)
humhub | 
humhub | No new migrations found. Your system is up-to-date.
.
.
humhub | /docker-entrypoint.sh: Config preprocessing ...
humhub | /docker-entrypoint.sh: installation active
humhub | /docker-entrypoint.sh: debug enabled
humhub | /docker-entrypoint.d/50-humhub-validate.sh
humhub | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
humhub | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
humhub | /docker-entrypoint.sh: Launching /docker-entrypoint.d/50-humhub-validate.sh
humhub | validating ...
humhub | 
humhub | *** Performing database integrity checks
humhub | 
.
.
.
humhub | 
humhub | *** All integrity checks done
humhub | 
humhub | /docker-entrypoint.sh: Configuration complete; ready for start up
humhub | /docker-entrypoint.sh: Entrypoint finished! Launching ...
humhub | nginx: [emerg] "keepalive_timeout" directive invalid value in /etc/nginx/nginx.conf:29
humhub | [28-Oct-2020 08:19:48] NOTICE: fpm is running, pid 36
humhub | [28-Oct-2020 08:19:48] NOTICE: ready to handle connections
humhub | nginx: [emerg] "keepalive_timeout" directive invalid value in /etc/nginx/nginx.conf:29
humhub | nginx: [emerg] "keepalive_timeout" directive invalid value in /etc/nginx/nginx.conf:29
.
.
-
```

**Comment by mriedmann** [comment] 2020-10-28 12:16
Ok thx for the data. 

This part is very interesting:
```
humhub | /docker-entrypoint.sh: Config preprocessing ...
humhub | /docker-entrypoint.sh: installation active
humhub | /docker-entrypoint.sh: debug enabled
humhub | /docker-entrypoint.d/50-humhub-validate.sh
humhub | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
humhub | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
humhub | /docker-entrypoint.sh: Launching /docker-entrypoint.d/50-humhub-validate.sh
humhub | validating ...
humhub | 
humhub | *** Performing database integrity checks
humhub | 
.
.
.
humhub | 
humhub | *** All integrity checks done
humhub | 
humhub | /docker-entrypoint.sh: Configuration complete; ready for start up
humhub | /docker-entrypoint.sh: Entrypoint finished! Launching ...
```
It doesn't show the script `60-nginx-config.sh` running. Can you please make sure that the `/docker-entrypoint.d/` folder inside the image contains this file? Also maybe try to pull the image again (`docker pull mriedmann/humhub:1.6.3`).

 Here is my test output with the newest 1.6.3 image from docker-hub and your docker-compose file (first installed with 1.6.2 and then switched to 1.6.3)

```
/docker-entrypoint.sh: Config preprocessing ...
/docker-entrypoint.sh: installation active
/docker-entrypoint.sh: debug enabled
/docker-entrypoint.d/50-humhub-validate.sh
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/50-humhub-validate.sh
validating ...

*** Performing database integrity checks
.
.
.
*** All integrity checks done

/docker-entrypoint.sh: Launching /docker-entrypoint.d/60-nginx-config.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
/docker-entrypoint.sh: Entrypoint finished! Launching ...
```
Everything seems to work fine. Please check the `/docker-entrypoint.d/` folder, besides that, I am a bit clueless here, to be honest. Please keep us posted!

**Comment by s2074135** [comment] 2020-10-29 10:28
@mriedmann , thank you for the checking the logs.

> > Can you please make sure that the /docker-entrypoint.d/ folder inside the image contains this file?

Yes the file does indeed exist in the folder. I can even execute that script and it creates the nginix.conf file correctly. The script also has the same permissions as 50-humhub-validate.sh, which is being executed. It seems that the file is being ignored or somehow fails silently.

In the mean time, I have removed all docker humhub images (docker rmi), restarted the docker daemon and, just for good measure, rebooted the system. No change so far.

**Comment by mriedmann** [comment] 2020-10-29 14:17
absolutely fascinating. You could have a look at `https://github.com/mriedmann/humhub-docker/blob/master/docker-entrypoint.sh#L247` and run the `find` command inside the container (`find "/docker-entrypoint.d/" -follow -type f -print | sort -n`). 
Also could you please provide your system-disto, docker, and docker-compose versions? 
We are really fishing in the dark here, any information could help.

**Comment by s2074135** [comment] 2020-10-29 16:59
@mriedmann 
Docker version 19.03.13, build 4484c46d9d
Ubuntu 20.04.1 LTS
docker-compose version 1.25.0, build unknown

Just to make sure, it isn't a data related problem (we migrated the humhub data set several times over from older versions and even non docker versions), I removed all data volumes and run Humhub in "initialization mode". This did not trigger the error and nginx.conf was populated properly.

It looks like, the error is data related. This would also explain, why you are not experiencing any problems but we do. But how is it possible for my data set to stop that script from executing correctly? Very strange....

**Comment by mriedmann** [comment] 2020-10-29 19:29
Could you please check if the `50-humhub-validate.sh` returns a 0 exit code (`echo $?`). Also please try to replace `set -e` with `set -eo pipefail` in `docker-entrypoint.sh`. You can also try to add a `set +x` at the top to see some more output. My guess is that something is failing silently in the pipeline at https://github.com/mriedmann/humhub-docker/blob/master/docker-entrypoint.sh#L247 leading to an silent pipefail.

**Comment by s2074135** [comment] 2020-10-30 18:57
@mriedmann thanks for the hints, they got me on the right track. When adjusting the shell script 50-humhub-validate.sh to this version:

```
#!/bin/sh

HUMHUB_INTEGRITY_CHECK=${HUMHUB_INTEGRITY_CHECK:-1}

if [ "$HUMHUB_INTEGRITY_CHECK" != "false" ]; then
	echo "validating ..."
	if ! true; then      # Original version is: if ! php ./yii integrity/run; then
		echo "validation failed!"
		exit 1
	fi
else
	echo "validation skipped"
fi
```
The nginix.conf file gets created without a hitch. Currently my take on the issue is:

`php ./yii integrity/run`

is somehow not happy with the state of my DB and returns a non zero exit code (theory), which stops the while loop in docker-entrypoint.sh from executing any further (verified).

From the DB integrity check, I get quiet a lot of the following messages:

>  Deleting activity id 407 without existing target! (humhub\modules\user\models\Follow) (yes|no) [no]:Deleting activity id 407 without existing target! (humhub\modules\user\models\Follow) (yes|no) [no]:Deleting activity id 548 without existing target! (humhub\modules\user\models\Follow) (yes|no) [no]:Deleting activity id 658 without existing target! (humhub\modules\user\models\Follow) (yes|no) [no]:Deleting activity id 663 without existing target! (humhub\modules\user\models\Follow) (yes|no) [no]:Deleting activity id 676 without existing target! (humhub\modules\user\models\Follow) (yes|no) [no]:Deleting activity id 680 without existing target! (humhub\modules\user\models\Follow) (yes|no) [no]:Deleting activity id 687 without existing target! (humhub\modules\user\models\Follow) (yes|no) [no]:Deleting activity id 692 without existing target! (humhub\modules\user\models\Follow) (yes|no) [no]:Deleting activity id 708 without existing target! (humhub\modules\user\models\Follow)  

Since no one is pressing yes or no in that script :-), this messages are displayed at every start of humhub. Could this be the root cause of the 60-nginx-config.sh not being executed?

Regards Thomas

**Comment by s2074135** [comment] 2020-10-30 19:41
After fixing the errors from the DB (php ./yii integrity/run), the container now starts up and nginx.conf gets properly created.

So a possible solution to this problem is:

1. enter into the running Humhub container (`docker exec -it ... sh`)
2. run the command `php /var/www/localhost/htdocs/protected/yii integrity/run` (your path to yii might be different)
4. answer all questions with 'yes' (read the question first though)
5. exit and restart the container

@mriedmann thank you for your help and thanks as well for letting us use a dockerized version of Humhub!

**Comment by mriedmann** [comment] 2020-10-30 23:40
Good to hear, no problem! I will look into it a bit more, because this behavior is not as intended. Thx for the debugging :).
I leave this open till we fixed the "silent fail". Maybe someone else hits this issue.

**Comment by mriedmann** [comment] 2021-08-09 10:54
If someone hits this, please comment. Will reopen if needed.

**Comment by Jeraimee** [comment] 2023-06-26 18:49
Ran into this 2 days ago. Wiped the DB before investigating further due to tests. If it's a user-delete issue I should run into it again.

**Comment by me2000** [comment] 2023-06-29 09:54
Ran into this. The reason is `/docker-entrypoint.d/50-humhub-validate.sh`. When validating for some errors yii is asking for confirmation (yes|no) which the script of course cannot give. The script fails and the other scripts are not executed anymore so that the nginx.conf is not valid.

Fix for me is to do
` "docker exec -it <CONTAINER_NAME> sh
cd /var/www/localhost/htdocs/protected
/docker-entrypoint.d/50-humhub-validate.sh`
and then type in "yes" when needed.

A final solution could be to change line 7 in `/docker-entrypoint.d/50-humhub-validate.sh` to
`if ! php ./yii integrity/run --interactive 0`
but needs to be tested.

**Closed** 2023-07-24 09:40 UTC
Labels: bug
